version: '2'
services:
    jhipstercourierapplication-app:
        image: jhipstercourierapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstercourierapplication-mysql:3306/jhipstercourierapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstercourierapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipstercourierapplication-mysql
